#!groovy
library identifier: 'jenkins-pipeline-demo-lib@master',
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/hofmanr/jenkins-pipeline-demo-lib.git'])

pipeline {
    agent any
    stages {
        stage('Audit tools') {
            steps {
                auditTools()
            }
        }
    }
}