library identifier: 'jenkins-pipeline-demo-lib@master',
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/rhofman14/jenkins-pipeline-demo-lib.git'])

crossPlatformBuild repoName: 'sixeyed/pi-psod-pipelines',
        linuxContext: 'm4',
        windowsContext: 'm4'