#!groovy
library identifier: 'jenkins-pipeline-demo-lib@master',
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/hofmanr/jenkins-pipeline-demo-lib.git'])

pipeline {
    agent any
    tools {
        maven 'Maven 3.8.6'
    }
    stages {
        stage('Audit tools') {
            steps {
                auditTools2 message: 'This is demo 2'
            }
        }
    }
}