pipeline {
    agent {
        dockerfile {
            dir 'm4'
            filename 'Dockerfile.sdk'
            args '-v $HOME/.m2:/root/.m2'
        }
    }
    stages {
        stage('Verify') {
            steps {
                sh '''
                    mvn --version
                    java -version
                '''
                sh 'printenv'
                sh 'ls -l "$WORKSPACE"'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Unit Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Smoke Test') {
            steps {
                sh '''
                    chmod +x ./jenkins/scripts/deliver.sh
                    ./jenkins/scripts/deliver.sh
                '''
            }
        }
    }
}