pipeline {
    agent {
        docker {
            image 'jenkins/agent-maven-jdk11'
            args '-v $HOME/.m2:/home/jenkins/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh '''
                chmod +x ./jenkins/scripts/deliver.sh
                ./jenkins/scripts/deliver.sh
                '''
            }
        }
    }
}