def image

pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    image = docker.build("hofmanr/maven-jdk11:$BUILD_NUMBER", "--pull -f jenkins/m4/Dockerfile jenkins/m4")
                }
            }
        }
        stage('Smoke Test') {
            steps {
                script {
                    container = image.run()
                    container.stop()
                }
            }
        }
//        stage('Push') {
//            steps {
//                script {
//                    withDockerRegistry([credentialsId: "docker-hub", url: "" ]) {
//                        image.push()
//                    }
//                }
//            }
//        }
    }
}
